#
# Master conda environment for prettymol.
#
# You can create and update the environment with conda devenv
#   conda devenv
# Or with mamba (recommended)
#   conda devenv --print >environment.yml && mamba env update -f environment.yml --prune
#
# This is an experiment & develop environment.
# Various environment requisites can be activated / deactivated using environment variables, like:
#   WITH_MANIMGL="" WITH_MANIM_COMMUNITY=TRUE conda devenv
# See the includes section below for more info.
#
# Usage depends on conda-devenv:
#   https://github.com/ESSS/conda-devenv
# So run once:
#   conda install conda-devenv -c conda-forge -n base
#
# We also recommend using mamba as a drop-in replacement to conda:
#   https://github.com/mamba-org/mamba
# So run once:
#   conda install mamba -c conda-forge -n base
#
{% set PRETTYMOL_DEVEL = os.environ.get('PRETTYMOL_DEVEL', False) %}

name: prettymol

channels:
  - conda-forge

dependencies:
  - python>=3.8
  - pip
  - pip:
    - "-e ."  # [ PRETTYMOL_DEVEL ]

includes:

#
# manim's little mess. See:
# https://3b1b.github.io/manim/development/about.html
#

{% set with_manimgl = os.environ.get('WITH_MANIMGL', False) %}
  - {{ root }}/conda/units/manimgl.devenv.yaml             # [with_manimgl]
{% set with_manim_community = os.environ.get('WITH_MANIM_COMMUNITY', True) %}
  - {{ root }}/conda/units/manim-community.devenv.yaml             # [with_manim_community]

#
# programmatic video editing batteries
#

{% set with_video_utils = os.environ.get('WITH_VIDEO_UTILS', True) %}
  - {{ root }}/conda/units/video.devenv.yaml             # [with_video_utils]


{% set with_cheminformatics = os.environ.get('WITH_CHEMINFORMATICS', True) %}
  - {{ root }}/conda/units/cheminformatics.devenv.yaml             # [with_cheminformatics]
