#
# See also AUR package:
#   https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-manimlib
# specially the skipbuild part, I guess to disallow checking for dependencies
#
# FIXME: we need some things to happen in conda-forge for this to work properly
#        maybe I will do sometime
#

name: manim
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.7
  - conda-forge::pip
  - conda-forge::ffmpeg
  - conda-forge::colour
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::pillow
  - conda-forge::tqdm
  - conda-forge::opencv
  - conda-forge::cairo
  - conda-forge::pycairo
  - conda-forge::pydub
  # in conda-forge sox is only available for linux and mac atm
  - conda-forge::sox
  # at the moment conda-forge only provides texlive-core; enough?
  - conda-forge::texlive-core

  # only needed in windows
  # - pyreadline

#
#  - pip:
#    - manimlib
#    or install from github itself
#      hardcoded dependencies there are probably not needed?
#      the aur package does not honor them
#      use docker if things go ugly
#
